### ISSUE TITLE
failure when passing the "preservekeys" argument since it returns a dictionary instead of a list

### ISSUE THREAD

**Issue by teriyakichild** [teriyakichild/zabbixctl#10]
zabbixctl -H zabbix.yourdomain.com get host  -a 'preservekeys=true'
Traceback (most recent call last):
  File "/home/user/.virtualenvs/zabbixctl/bin/zabbixctl", line 9, in <module>
    load_entry_point('zabbixctl==1.1.3', 'console_scripts', 'zabbixctl')()
  File "/home/user/zabbixctl/zabbixctl/cli.py", line 152, in main
    cli.execute()
  File "/home/user/zabbixctl/zabbixctl/cli.py", line 119, in execute
    if final[0].get(key, None):
KeyError: 0

**Comment by teriyakichild** [comment]
resolved with https://github.com/teriyakichild/zabbixctl/commit/9734770c3f7552c496d5eb61060faea2ae46fe79
